# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailgun', '0002_auto_20181104_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='db_account',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='db_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='mailgun.EmailThread'),
        ),
    ]
